name: Build 42_ft_printf
on:
    push:
        branches: [ "master" ]
    pull_request:
jobs:
    build-42_ft_printf:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build and Test
              run: |
                make fclean
                make